### PR TITLE
T16 Popups working

### PR DESCRIPTION
**Pull request by ramandeepjain**
The popups are working. It is possible to custom the sieve size.

### CODE REVIEW

**Comment by rabbl** [comment]
Hi Ramandeep... 
there are some conflicts due to the bigger changes we have done 
can you solve this and do a pull request again?!

**Comment by ramandeepjain** [comment]
Ok. I'll do it.

**Comment by ramandeepjain** [comment]
Hi Ralf, after the merge the dashboard is not visible anymore. Is it because of the new webpack? 
I only see Home.

**Comment by rabbl** [comment]
It's running well after remove the node_modules-folder and run yarn install again.
So, I'll merge this pull request.

**Pull request merged**
